name: test
on: push
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: go test ./...
